### ISSUE TITLE
Limit amount of running jobs

### ISSUE THREAD

**Issue by Firesphere** [silverstripe-australia/silverstripe-queuedjobs#100]
It would be nice, if there could be a limit to the amount of jobs running. e.g. when there are 4 processes running, don't start another one.

**Comment by tractorcow** [comment]
You can specify rules which control max processes using yml.

See https://github.com/silverstripe-australia/silverstripe-queuedjobs/blob/master/docs/en/configuring-multi-process-execution.md for docs.
