### ISSUE TITLE
Update asyncphp/doorman to ^3.0

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe-australia/silverstripe-queuedjobs#122]
Just logging this here to help alleviate a composer dependency chain breaking with the latest SS4 builds:

* silverstripe/framework requires **nikic/php-parser ^2 || ^3**
* silverstripe/activedirectory requires *silverstripe/queuedjobs* ^3.0@dev
* silverstripe/queuedjobs requires asyncphp/doorman ~1.2
* asyncphp/doorman requires jeremeamia/superclosure ^1.0
* jeremeamia/superclosure requires **nikic/php-parser ~0.9**

This means you can't update the framework and CMS if you've got queuedjobs installed.

The latest version of asyncphp/doorman (3.0.0) requires superclosure ^2.0 which in its latest version (2.3.0) has a much looser constraint for php-parser: ^1.2 | ^2.0 | ^3.0, which would be compatible with the framework.

I'm not familiar with doorman, but can have a crack at updating this requirement and will PR a fix.

**Comment by sminnee** [comment]
If doorman can use superclosure 2.3.0 we should be okay.

**Comment by sminnee** [comment]
FYI @robbieaverill doorman was built by @assertchris

**Comment by robbieaverill** [comment]
Closing - done in #125
