### ISSUE TITLE
Ensure multiple queue processors don't run duplicate jobs

### ISSUE THREAD

**Issue by sminnee** [silverstripe-australia/silverstripe-queuedjobs#26]
Right now queuedjobs seems to rely on only 1 copy of the worker process running. If you have multiple workers running—e.g. for scaling, or because you have more than 1 server and it's easier to configure them the same—race conditions can lead to a single job being executed more than once.

It would be better if the queuedjobs module guarded against this. Presumably this would involve updating the status from the non-running state to the running state in a single command:

    UPDATE "QueuedJobDescriptor" SET "JobStatus" = 'Running'
    WHERE "JobStatus" IN ('New', 'Waiting') AND "ID" = $jobID

If this command didn't affect any rows, then we know someone else as handled the job and we can exit without running the job.

I guess this goes in here? https://github.com/silverstripe-australia/silverstripe-queuedjobs/blob/master/code/services/QueuedJobService.php#L395

**Comment by stojg** [comment]
>Given that the first execution of job code happens in QueuedJobService::initialiseJob(), it's probably the best point to do the explicit update-mark-running/row-count-check at that point

:+1: 

I haven't found any other way to do this that is reliable without doing database specific custom queries.

**Comment by silverstripe-elliot** [comment]
@stojg could you use database locks? Something like this: https://github.com/silverstripe-elliot/silverstripe-queuedjobs/commit/f52fdbe6fd9e85fe6378cba9246216f6f1865189

**Comment by halkyon** [comment]
Affected rows pull request: https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/32

**Comment by mateusz** [comment]
@silverstripe-elliot the solution proposed in #32 is more hacky, but at least it will work across all databases. I'm looking at you, [MariaDB/Galera](https://mariadb.com/kb/en/mariadb/mariadb-galera-cluster-known-limitations/) :-)

This might not solve the problem in 100% though :-) I haven't really researched how atomic are the UPDATE queries and how isolated they are (across all databases we support), but there is a possibility that the "affectedRows" method is not race-proof.

**Comment by sminnee** [comment]
I raised this ticket originally and #32 is certainly the kind of fix that I had in mind. I'm happy to close this now that it's been #32 has been merged.
