### ISSUE TITLE
Setting QueuedJobService.max_init_jobs seems to have no effect (Doorman)

### ISSUE THREAD

**Issue by micschk** [silverstripe-australia/silverstripe-queuedjobs#297]
I (think I) configured the QueuedJobService (with Doorman runner) to initialize at most 1 job at a time with the below config. But this doesn't seem to take effect as it still marks any waiting jobs to 'initializing' (eg up to 20 simultaneously).

```yml
Symbiote\QueuedJobs\Services\QueuedJobService:
  max_init_jobs: 1
```

**Comment by mfendeksilverstripe** [comment]
`max_init_jobs` is not a hard limit but rather a soft limit. This limit can be bypassed to some degree but it eventually stops the jobs from switching to init state. This setting is meant to act as a last ditch effort to stop a poorly configured queue setup or server instance in some weird state from switching all your jobs to init state.

Currently, this check is done just before running the queue but this is not sufficient and the check should be done also within the loop. I already fixed this in [this PR](https://github.com/symbiote/silverstripe-queuedjobs/pull/287/files#diff-255a2898e87bc13a20569c932b00f920R137).

**Comment by bergice** [comment]
Considering this resolved.
