### ISSUE TITLE
RunBuildTaskJob will mark any job longer than 5 mins as stalled

### ISSUE THREAD

**Issue by chillu** [silverstripe-australia/silverstripe-queuedjobs#325]
`RunBuildTaskJob` is a convenient shortcut for running `BuildTask` classes which usually rely on a CLI task runner outside of queues. The job simply calls `BuildTask->run()`, without any further knowledge of the build task running in a queue context.

This means the build task doesn't increment `QueuedJobsDescriptor->StepsProcessed`, because it doesn't know about it.
Which is an issue, since every time `ProcessJobQueueTask` is called, `QueuedJobService->checkJobHealth()` is called. This logic will mark jobs as "stalled" if they meet two criteria: Their `Expiry` date hasn't been reached (defaulting to 5 mins), and `"StepsProcessed" = "LastProcessedCount"`. Since the build task never increments `StepsProcessed`, it marks the job as stalled, causing it to restart until the threshold is reached. Unless the next job execution relies on caches which make it run less than 5 mins, it'll keep getting marked as stalled until it's paused.

Note that the entire time, the job is executing commands (which can often be observed by writing records to `QueuedJobDescriptor->SavedJobMessages`. It's just not counting up steps.

As far as I can tell, this is a regression from https://github.com/symbiote/silverstripe-queuedjobs/commit/4397484ebf1e22f4172ced6d86922cad73daf611. Having multiple steps in your job used to be [recommended](https://github.com/symbiote/silverstripe-queuedjobs/blob/4/docs/en/defining-jobs.md#multiple-steps-multiple-steps), but now it is effectively required for longer running tasks.

@mfendeksilverstripe Any ideas?

**Comment by brynwhyman** [comment]
Ah, we might have actually hit the same issue recently.... https://github.com/silverstripe/silverstripe-externallinks/issues/69

**Comment by mfendeksilverstripe** [comment]
Thanks for feedback @chillu . I don't consider this a regression but reliance on partially broken behaviour. I would argue that current behaviour is correct / expected in general. Specifically for this case though maybe we need some follow up changes. Here is a bunch of ideas on how to tackle the problem.

* you can update the `worker_ttl` via the configuration API so it matches your project specific needs or disable health check via `disable_health_check` (project specific, low effort, global impact)
* we could refine the stalled jobs check to exclude tasks which run as jobs (module specific, low effort, specific impact)

I think I can push up a PR quite quickly.

**Comment by mfendeksilverstripe** [comment]
Here is the PR which should cover the above mentioned case.

https://github.com/symbiote/silverstripe-queuedjobs/pull/326

Keen on your feedback @chillu

**Comment by brynwhyman** [comment]
Assuming this is causing issues like this: https://github.com/silverstripe/silverstripe-externallinks/issues/69 I'm going to mark this is as impact/critical. Happy to reassess this if this isn't deemed to cause the issue that I've linked.

**Comment by Cheddam** [comment]
Resolved via #326 (backported and released in [`4.6.2`](https://github.com/symbiote/silverstripe-queuedjobs/releases/tag/4.6.2)) and #327.
