### ISSUE TITLE
BUG: Zero values for integers and floats within queued job rule are not allowed

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe-australia/silverstripe-queuedjobs#338]
# Zero values for integers and floats within queued job rule are not allowed

Zero values for integers and floats within queued job rule are needed to cover the cases where high memory or processor use should prevent any new jobs from being started. This is currently impossible to set even though it's internally supported within the AsyncPHP\Doorman\Rules\InMemoryRules::canRunTask.

Fixed in https://github.com/symbiote/silverstripe-queuedjobs/pull/337

**Comment by maxime-rainville** [comment]
Resolved by https://github.com/symbiote/silverstripe-queuedjobs/pull/337
