### ISSUE TITLE
Cron runner does not work with 4.7.0

### ISSUE THREAD

**Issue by stnvh** [silverstripe-australia/silverstripe-queuedjobs#346]
Upgrading to 4.7.0 with cron setup from 4.6.x does not find any queued jobs, returns the date and "No new jobs on queue 2" despite new queued jobs existing.

Is there undocumented breaking changes in the 4.7.0 release? I can't seem to find anything other than health check changes - could this be related? Thanks

EDIT: this was actually due to british summer time clocks going forward and server time not being configured to Europe/London. Fixed by running  `sudo dpkg-reconfigure tzdata` - a separate issue which may be worth documenting or jobs run an hour late! (those with "Start After")

**Comment by dhensby** [comment]
It's best to configure your server to run UTC on the system and the DB layer, then times can be "localised" to the user via the front end, but all timing dealt with in UTC.

I don't think this is a bug with this library, it's a server configuration issue.

**Comment by stnvh** [comment]
Definitely not a bug in the library. 

The issue here was the date/time passed through when calling `queueJob` was a DateTime instance set to London timezone, we use Fluent across the site with jobs being queued in each locale so this needed to be standardised. Suggestion for this specific case was to ensure the instance matches the server timezone regardless of whether its UTC or not
