### ISSUE TITLE
Can't get job to process reliably

### ISSUE THREAD

**Issue by altwohill** [silverstripe-australia/silverstripe-queuedjobs#351]
I have a job that needs to process ~3000 member records with a process that takes a couple of seconds each time.

I'm having no luck getting it to work. It either gets stuck on _Initialising_, or stops after ~70 records due to lack of memory and then won't initialise again.

Here's my code and config: https://gist.github.com/altwohill/fd51f3af0592d08c21d23515aa564477

What am I doing wrong?

**Comment by emteknetnz** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and we don't provide support via the issue tracker.

A good place to get support is on the [Silverstripe community slack channel](http://silverstripe.org/slack).

Sorry we can't be of more help and good luck resolving your problem.
