### ISSUE TITLE
Empty INFO messages each time process() is called

### ISSUE THREAD

**Issue by micschk** [silverstripe-australia/silverstripe-queuedjobs#357]
For some reason an empty message gets logged upon each call to process;

<img width="330" alt="Screenshot 2021-09-12 at 07 13 47" src="https://user-images.githubusercontent.com/1005986/132973149-7b4b8644-5bda-43da-b63d-fdd689e586f9.png">

(I can confirm #353 fixes this)

**Comment by emteknetnz** [comment]
Linked PR has been merged and released as 4.9.1
