### ISSUE TITLE
Array to String conversion in checkJobHealth()

### ISSUE THREAD

**Issue by phptek** [silverstripe-australia/silverstripe-queuedjobs#368]
`symbiote/silverstripe-queuedjobs:^4.8`

Looking at `QueuedJobService:: checkJobHealth()`, it returns `array`. However, in `CheckJobHealthTask.php:44` logic is attempting to concatenate its return value onto a string.

` echo $stalledJobCount === 0 ? 'All jobs are healthy' : 'Detected and attempted restart on ' . $stalledJobCount`

...which should probably read:

` echo $stalledJobCount === 0 ? 'All jobs are healthy' : 'Detected and attempted restart on ' . sizeof($stalledJobCount)`

**Comment by emteknetnz** [comment]
Fix was released in 4.9.0

https://github.com/symbiote/silverstripe-queuedjobs/commit/9c6f4c09397e3b77a3bd7f313def20b4dd7ef93f
