### ISSUE TITLE
Default jobs recreated multiple times

### ISSUE THREAD

**Issue by renskorswagen** [silverstripe-australia/silverstripe-queuedjobs#376]
When my 3 cron jobs runs queue 1, 2 and 3 at the same time my default jobs are recreated three times. Am i doing something wrong?

```SilverStripe\Core\Injector\Injector:
  Symbiote\QueuedJobs\Services\QueuedJobService:
    properties:
      defaultJobs:
        Import:
          type: 'ImportJob'
          filter:
            JobTitle: 'Import daily'
          recreate: 1
          startDateFormat: 'Y-m-d H:i:s'
          startTimeString: 'next weekday 1:00'
          construct:
            subsiteId: 5
            title: 'Import daily'

**Comment by emteknetnz** [comment]
If you're happy to use a non-stable branch, in this case requires `4.x-dev`, then this recently merged pull-request can limit this to a single queue type

https://github.com/symbiote/silverstripe-queuedjobs/pull/365
