### ISSUE TITLE
UI doesn't provide usefull search fields

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe-australia/silverstripe-queuedjobs#386]
The UI doesn't provide any sensible job filters beyond the job title.

## Acceptance criteria
- [x] User can filter by Job Type
- [x] Users can filter by Job status

## Pull request
- https://github.com/symbiote/silverstripe-queuedjobs/pull/385

**Comment by GuySartorelli** [comment]
PR merged and no remaining acceptance criteria. Closing.
