### ISSUE TITLE
SS5 Queued Jobs 5.0.0: Gridfiled Admin pagination missing after search

### ISSUE THREAD

**Issue by blueo** [silverstripe-australia/silverstripe-queuedjobs#405]
I have job's admin with multiple pages of new and completed jobs. I want to filter these to see only the 'new' jobs but after selecting Job Type "new" and searching the pagination is no longer available. 

This is very useful for inspecting the queue and estimating time to completion etc. 

## Acceptance criteria
- Pagination shows on Gridfiled after the search criteria is applied.
- Pagination shows on ModelAdmin after the search criteria is applied. 
- Behat test are added to cover this scenario
 
## Notes
- Problem is not with JobAdmins ... all gridfield are affected.
- Only tested on CMS 5 so far. Just need to double check that CMS 4 is not affected.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10828
- https://github.com/silverstripe/silverstripe-admin/pull/1530

**Comment by emteknetnz** [comment]
Linked framework PR has been merged and released as [5.0.8](https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.8)
