### ISSUE TITLE
OOM errors leave queuedjobs unrecoverable

### ISSUE THREAD

**Issue by tractorcow** [silverstripe-australia/silverstripe-queuedjobs#41]
There is memory protection in queuedjobs, but it's more of a mechanism for reducing the chance of this happening rather than recovering from such a state.

What normally happens is that the job will have JobStatus = 'Running', and when the job detects that memory is low it sets the job to 'Waiting' and restarts.

If this catch fails to trigger then the job will be left with status = waiting and there won't be any indication that the queue has failed (unless you explicitly check the server logs for the error message).

**Comment by tractorcow** [comment]
Ok, it looks like in our case QueuedJobsService::$memory_limit was EXACTLY set to the server limit, so there was no chance for the queue to safely escape.

**Comment by tractorcow** [comment]
I've come up with a fix; Hope it meets the expected high quality of contribution. ;D

**Comment by nyeholt** [comment]
It's a problem with any `fatal` error, in that the job is left "Running". There's some logic in `checkJobHealth` that will actually see whether a descriptor has incremented its "steps processed" field (ie currentStep from within the job), but that only kicks in if StepsProcessed is greater than 0. One way to work around things is to set currentStep in the constructor when first creating the job...

**Comment by tractorcow** [comment]
Ok thanks @nyeholt :D 

I wonder if we could improve the check to work even if StepsProcessed is 0; I've raised an internal ticket pointing at this open source issue and will try to schedule some time to properly resolve this.

**Comment by tractorcow** [comment]
Yet another potential improvement at https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/43

It doesn't stop the module from crashing, but ensures that jobs are recoverable.

**Comment by tractorcow** [comment]
I think this is issue obsolete with the new doorman backend. :)
