### ISSUE TITLE
Clear jobs from the db

### ISSUE THREAD

**Issue by benmanu** [silverstripe-australia/silverstripe-queuedjobs#44]
So as not to clog up the db there should be a way to clear jobs from the db after a set interval, or after x completions. Use case being I have a job that runs every minute, over the course of a day thats 1440 new records.

**Comment by phptek** [comment]
@benmanu Nice idea, been meaning to submit something similar. My idea, possibly in addition, is to add checkboxes to the GridField located at /admin/queuedjobs that allows users to perform a batch action to "delete", "pause" and "run" >1 job at a time. It's a real PIA when a frequent job fails (e.g. running out of memory on CWP small instances) and I need to delete multiple "broken" jobs and start afresh.
