### ISSUE TITLE
ProcessJobQueueTask.php listJobs() missing

### ISSUE THREAD

**Issue by johannesx75** [silverstripe-australia/silverstripe-queuedjobs#80]
In line 24 through 28 of ProcessJobQueueTask.php seems to be code for a list helper:
```php
if($request->getVar('list')) {
	// List helper
	$this->listJobs();
	return;
}
```
Calling list on the task fails because the method 'listjobs' does not exist on 'ProcessJobQueueTask'.
Is this obsolete code or is this listJobs somewhere else and the call just needs to be updated?

**Comment by tractorcow** [comment]
It looks like code that was once refactored incorrectly.

Want to dig it up and add it back in? :p

**Comment by johannesx75** [comment]
I can't find any related code for it in the master branch history. From what I can tell the call to listJobs() appears in 84741b810a93590487f5bb65be5617bddc043711 for the first time. But without any actual code. That was the commit, that added the new core engine. Is there an extra branch where that was originally developed in?

**Comment by tractorcow** [comment]
That would be at https://github.com/open-sausages/silverstripe-queuedjobs/commits/feature/add-additional-core-engine

**Comment by johannesx75** [comment]
Ok, I found the original code in 4f1ee1c98344c3600e9cf17d38b62cbca82d17d4. But since writeLogLine moved to BaseRunner.php I moved the listJobs function there as well. I'm not certain that this is the best place for this code, or that this function is even needed by anyone. But at least it works again. ;)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/81
