### ISSUE TITLE
CMS requirement

### ISSUE THREAD

**Issue by swilsonalfa** [silverstripe-australia/silverstripe-queuedjobs#86]
Hi There,
Is there a specific reason why silverstripe-cms is included as a requirement? I've been using this module with a framework only project and it's working fine. I notice that the examples are mainly oriented towards CMS users however.

Thanks for your consideration.

**Comment by tractorcow** [comment]
It probably doesn't need CMS; It was CMS-inclusive from the initial commit.

Would you like to test removing it in a PR?

**Comment by swilsonalfa** [comment]
PR submitted #87. All tests completed successfully. I'll close this one now.
