### ISSUE TITLE
AbstractQueuedJob not really abstract

### ISSUE THREAD

**Issue by Firesphere** [silverstripe-australia/silverstripe-queuedjobs#89]
The functions that should be abstracts (like process()), aren't, thus not enforcing implementation.

**Comment by tractorcow** [comment]
Do you want to pull request to that effect? It'll probably have to be a new major version though.

**Comment by Firesphere** [comment]
I could have a go at it next hackday.

**Comment by Firesphere** [comment]
Fixed in the pull request.
