### ISSUE TITLE
DB error when running job "Prepared statement needs to be re-prepared"

### ISSUE THREAD

**Issue by sheadawson** [silverstripe-australia/silverstripe-queuedjobs#92]
There errors are being logged occasionally with some of my queued jobs. Any ideas? What do the question marks mean in the query?

![screen shot 2016-04-13 at 8 28 10 am](https://cloud.githubusercontent.com/assets/1166136/14474547/c5fac6e8-0151-11e6-8d41-100e8fbe4d77.png)
![screen shot 2016-04-13 at 8 28 25 am](https://cloud.githubusercontent.com/assets/1166136/14474552/c827a2f6-0151-11e6-8091-2fdad04e8db2.png)
![screen shot 2016-04-13 at 8 28 40 am](https://cloud.githubusercontent.com/assets/1166136/14474554/c95c68d2-0151-11e6-9221-60db18a7f194.png)

SS 3.2.0
QueuedJobs 2.8.4

**Comment by nyeholt** [comment]
The ? ? ? is just the prepared statement syntax - the actual values are bound in when the sql statement is 'prepared' by the DB before inserting the values. 

I've never seen the exception though (that the query needs to be re-prepared). Do you have a lot of things in your job queue before running the process task?

**Comment by sheadawson** [comment]
Hey thanks for the response, this turned out to be a server issue at the host, sorry! Closing..

**Comment by baukezwaan** [comment]
@sheadawson mind sharing what the host had changed at the server? We also run into these errors now and then (unrelated to QueuedJobs btw).

**Comment by sheadawson** [comment]
@baukezwaan actually it's not the host so much. The heart of the issue is this mysql bug https://bugs.mysql.com/bug.php?id=42041. Being on a shared host, our prepared statements were often breaking because other customers on the server were running regular mysql-dump processes

**Comment by tractorcow** [comment]
I think when running queuedjobs as a service, given the expected long-life expectancy of some queries, it may make sense to periodically flush all prepared statements.

It may be necessary to build in some kind of max-lifetime into the query API.
